---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


Minimal reproducible example: ranking of Computer Science programs by placement matrix. 

[Dataset from http://cs.brown.edu/people/apapouts/faculty_dataset.html].


```{r}
# Some old, old R code.

source("functions.R")

# Nowadays I only do it like this.

library(tidyverse)
data = read_csv("professors.csv")

# Rename to the columns I used in 2005.

combined = data %>% select(Doctorate, University, JoinYear, Bachelors) %>%
  mutate(Year = JoinYear,
         DegreeSchool = Doctorate,
         School = University) %>%
  mutate(DegreeSchool = DegreeSchool %>% str_replace(" - USA", ""))

# Build a symmetrical matrix

appts = make.appointments(combined, max.year = 2020, min.year = 2005)

# q is the transition likelihood. If it's 0, a very strong weight will be placed
# on placement at top schools; if it's 1, all schools will be treated equally.

(pagerank(appts, q = .1) * 100) %>% as_tibble(rownames = "school") %>% arrange(-V1) %>% rename(p = V1) %>%
head(30) %>% knitr::kable() %>% cat(sep="\n")

combined %>% filter(Year > 2000) %>% ggplot() + geom_histogram(aes(x=Year))
```
# Bootstrapping

A good way to get error bars would be to use bootstrap sampling. We didn't do this in the paper, but it gives a decent idea of the variability in this data.

```{r fig.height = 12, fig.width=8}
bootstrap = function() {
  sample = combined %>% ungroup %>% slice_sample(prop = 1, replace = TRUE)
  appts = make.appointments(sample, max.year = 2020, min.year = 2005)
  
  # q is the transition likelihood. If it's 0, a very strong weight will be placed
  # on placement at top schools; if it's 1, all schools will be treated equally.
  
  (pagerank(appts, q = .1) * 100) %>% as_tibble(rownames = "school") %>%
    mutate(score = V1)
}

samples = rerun(500, bootstrap())

p = samples %>% bind_rows() %>% group_by(school) %>% mutate(mean = mean(score), sd = sd(score)) %>%
  filter(mean > 0.1) %>%
  ggplot() + aes(x = reorder(school,mean), ymin = mean-sd, ymax = mean + sd, y = score) + coord_flip() + geom_boxplot() + scale_y_log10() + labs(title = "Ranking of Computer Science grad programs", subtitle = "by PhD placement, 2005-2015", caption = "Ben Schmidt, 2020")


p %>% ggsave(filename = "~/Dropbox/benschmidt.org/static/CS-rankings.png", width = 8, height = 12)
p
combined %>% filter(DegreeSchool=="University of California - Santa Barbara") %>% select(University, JoinYear)


```

Undergrad rankings based on grad school placement.

```{R}
combined = data %>% select(Doctorate, University, JoinYear, Bachelors) %>%
  mutate(Year = JoinYear,
         DegreeSchool = Bachelors,
         School = University) %>%
  mutate(DegreeSchool = DegreeSchool %>% str_replace(" - USA", ""))

bootstrap = function() {
  sample = combined %>% ungroup %>% slice_sample(prop = 1, replace = TRUE)
  appts = make.appointments(sample, max.year = 2020, min.year = 2005)
  
  # q is the transition likelihood. If it's 0, a very strong weight will be placed
  # on placement at top schools; if it's 1, all schools will be treated equally.
  
  (pagerank(appts, q = .1) * 100) %>% as_tibble(rownames = "school") %>%
    mutate(score = V1)
}

ug_samples = rerun(500, bootstrap())

ug = ug_samples %>% bind_rows() %>% group_by(school) %>% summarize(ug_mean = mean(score), ug_sd = sd(score))
g = samples %>% bind_rows() %>% group_by(school) %>% summarize(g_mean = mean(score), g_sd = sd(score))

library(ggrepel)
p = ug %>% inner_join(g) %>% filter(g_mean > 1 | ug_mean > 1) %>% ggplot() + geom_label_repel(aes(x = g_mean, y = ug_mean, label = school), size = 3) + scale_x_log10("Graduate score") + scale_y_log10("Undergrad score") + labs(title = "Comparison of placement of grad students (x axis) vs undergrads (y axis)") 

p %>% ggsave(filename = "~/Dropbox/benschmidt.org/static/Comparison of grad and undergrad rankings.png", plot = ., width = 7, height = 7)

```